// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechIn.StatusPage.UI.Data;

#nullable disable

namespace TechIn.StatusPage.UI.Storage.MySQL.Migrations;

[DbContext(typeof(StatusPageDbContext))]
partial class StatusPageDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("status_page")
            .HasAnnotation("ProductVersion", "8.0.22")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("TechIn.StatusPage.Core.Models.HealthSnapshot", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                b.Property<string>("Description")
                    .HasMaxLength(2048)
                    .HasColumnType("varchar(2048)")
                    .HasColumnName("description");

                b.Property<TimeSpan?>("Latency")
                    .HasColumnType("time(6)")
                    .HasColumnName("latency");

                b.Property<string>("ServiceName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("service_name");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("varchar(32)")
                    .HasColumnName("status");

                b.Property<DateTimeOffset>("Timestamp")
                    .HasColumnType("datetime")
                    .HasColumnName("timestamp");

                b.HasKey("Id");

                b.HasIndex("ServiceName")
                    .HasDatabaseName("ix_snapshots_service_name");

                b.HasIndex("Timestamp")
                    .HasDatabaseName("ix_snapshots_timestamp");

                b.HasIndex("ServiceName", "Timestamp")
                    .HasDatabaseName("ix_snapshots_service_name_timestamp");

                b.ToTable("snapshots", "status_page");
            });
#pragma warning restore 612, 618
    }
}
