// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechIn.StatusPage.UI.Data;

#nullable disable

namespace TechIn.StatusPage.UI.Storage.SQLite.Migrations
{
    [DbContext(typeof(StatusPageDbContext))]
    [Migration("20260225224137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("status_page")
                .HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TechIn.StatusPage.Core.Models.HealthSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("Latency")
                        .HasColumnType("TEXT")
                        .HasColumnName("latency");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_snapshots_service_name");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_snapshots_timestamp");

                    b.HasIndex("ServiceName", "Timestamp")
                        .HasDatabaseName("ix_snapshots_service_name_timestamp");

                    b.ToTable("snapshots", "status_page");
                });
#pragma warning restore 612, 618
        }
    }
}
